name: "Test"
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
  push:
  schedule:
    - cron:  '0 */6 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: fr_FR.UTF-8
      run: |
          sudo locale-gen fr_FR.UTF-8
          sudo update-locale LANG=fr_FR.UTF-8
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-22.11
    - name: Install dependencies
      run: nix develop --command bash -c "cd univers && yarn install"
    - name: Fetch data
      run: nix develop --command bash -c "cd univers && yarn update_data"
    - name: Generate the search index
      run: nix develop --command bash -c "cd univers && yarn generate_index"
    - name: Rename files
      run: nix develop --command bash -c "cd univers && yarn rename_files"
    - name: Build website
      run: nix develop --command bash -c "cd univers && yarn build"
    - name: Copy files
      run: cp univers/{output,index}.*.json univers/build/
    - name: List results
      run: ls -alhR univers/build/
    - name: Push files to server
      env:
        dest: 'www@sciences.re:/home/www/sciences.re/postes'
      run: |
        echo "${{secrets.POSTES_DEPLOY_PRIVATE_KEY}}" > deploy_key
        chmod 600 ./deploy_key
        rsync -chav --delete \
        -e 'ssh -4 -p 2102 -i ./deploy_key -o StrictHostKeyChecking=no' \
        ./univers/build/ ${{env.dest}}
